#ifndef __dlgAbout__
#define __dlgAbout__

/**
@file
Subclass of lms8_dlgAbout_view, which is generated by wxFormBuilder.
*/

#include "lms8suiteApp_gui.h"

//// end generated include

/** Implementing lms8_dlgAbout_view */
class dlgAbout : public lms8_dlgAbout_view
{
	protected:
		// Handlers for lms8_dlgAbout_view events.
		void OnInit( wxInitDialogEvent& event );
		void OnbtnClose( wxCommandEvent& event );
	public:
		/** Constructor */
		dlgAbout( wxWindow* parent );
	//// end generated class members



};

#endif // __dlgAbout__
