#ifndef __LMS8dlgFullMessageLog__
#define __LMS8dlgFullMessageLog__

/**
@file
Subclass of dlgFullMessageLog_view, which is generated by wxFormBuilder.
*/

#include "utilities_gui.h"

//// end generated include
#include <deque>
/** Implementing dlgFullMessageLog_view */
class lms8_dlgFullMessageLog : public lms8_dlgFullMessageLog_view
{
protected:
	// Handlers for dlgFullMessageLog_view events.
public:
	/** Constructor */
	lms8_dlgFullMessageLog(wxWindow *parent);
	void AddMessages(const std::deque<wxString> &messages);
	//// end generated class members
};

#endif // __dlgFullMessageLog__
