#ifndef __LMS8dlgTempCalibrate__
#define __LMS8dlgTempCalibrate__

/**
@file
Subclass of dlgTempCalibrate_view, which is generated by wxFormBuilder.
*/

#include "utilities_gui.h"

#include "LMS8001.h"

//// end generated include
class LMScomms;
/** Implementing dlgDeviceInfo_view */
class lms8_dlgTempCalibrate : public lms8_dlgTempCalibrate_view
{
protected:
	// Handlers for dlgDeviceInfo_view events.
public:
	/** Constructor */
	//// end generated class members
	lms8_dlgTempCalibrate(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString &title = wxEmptyString, const wxPoint &pos = wxDefaultPosition, const wxSize &size = wxDefaultSize, long styles = 0);
	void Initialize(LMS8001 *pControl);

	void OnClick_btnCalibrate(wxCommandEvent &event);
	void OnClick_btnReset(wxCommandEvent &event);

protected:
	LMS8001 *lmsControl;
};

#endif // __dlgTempCalibrate__
