#ifndef __LMS8pnlMiniLog__
#define __LMS8pnlMiniLog__

/**
@file
Subclass of pnlMiniLog_view, which is generated by wxFormBuilder.
*/

#include "utilities_gui.h"
//// end generated include
#include <deque>
/** Implementing pnlMiniLog_view */
class lms8_pnlMiniLog : public lms8_pnlMiniLog_view
{
public:
	/** Constructor */
	lms8_pnlMiniLog(wxWindow *parent, wxWindowID id = wxID_ANY, const wxPoint &pos = wxDefaultPosition, const wxSize &size = wxDefaultSize, long style = wxTAB_TRAVERSAL);
	virtual void OnBtnClearClicked(wxCommandEvent &event);
	virtual void OnShowFullLog(wxCommandEvent &event);
	//// end generated class members
	void HandleMessage(wxCommandEvent &event);
	virtual void OnUpdateGUI(wxUpdateUIEvent &event);

protected:
	std::deque<wxString> mAllMessages;
	std::deque<wxString> mMessageList;
	int mNewMessages;
};

#endif // __pnlMiniLog__
